language: c
addons:
  apt:
    packages:
    - squashfs-tools
script: ./build
deploy:
  provider: releases
  api_key:
    secure: IUxqX9zeAQgR7rzVpLH7sj44JvCqCHNpEJxtwjLrn5573Pw/LBknZCIdmVUeVHqxfiQKVoOxwQ34y7oIBGwXcJWsZS3akxztuxJ0uzN9IK3M2EYvF/oflmaV0MtVKLsdGaDgmciawUXuYObeTdhdkNiEvVngNvp9b/GrClBxLH0wmHqm3LN/zYwQcafGq7s/5SaIzsiMABz0xD4ufy0PRO+RoenrbbncLxmE3vL9UFJJ2IV8eskYanf40EqLujNDeYiMOKUTW76f+Smf6k7FVIMC7GowkPLdEmPYNknNj+AC+KkPmokDaYGBtAc2nOKM9/730QEJe5N7j/tfktlica5wLMyJp77KwEv4WojTvIzY8Lm/JjeG//DueJ7fIKkvLk6kuQcAbClqYb3IGHuHepstO+Q6EvXNrAhR6zJ4Ce0pBK0WMZmpXZ6zpr0folNanrxlto6mfDL2OOpbkG7n7N3j8sEhQRkQpG/IsquJO7pUP5y2AWwxJ9T4kYydbWO4ua+YauOXA9+fMh8nqTjemR821eTd+a6NzgG5NwXXNV2M/3wPSqNz0B8EOK+FN1CGuMDR/GOe7FeuQjoB77k8nADWyO6Gv+9p+n1DQtvjdNG81P49qXF2O6KDkPQhTLtnKR/H4lQqLha8MLLuWfjDVJFePzEIUfoiuAG0fZDQyPQ=
  file: dist.tar.gz
  on:
    tags: true
