#!/bin/sh -ex
RELEASE="1.2.0.2"
PLATFORM="os.linux.x86_64"

TARBALL_URL="https://d3sqy0vbqsdhku.cloudfront.net/packages-bootstrap/${RELEASE}/meteor-bootstrap-${PLATFORM}.tar.gz"
wget -q "$TARBALL_URL"
tar -xzf "meteor-bootstrap-$PLATFORM.tar.gz"

mv .meteor/package-metadata rw
mkdir rw/packages

mksquashfs .meteor bootstrap.squashfs -no-progress -all-root

rm -rf .meteor
